{
  "openapi": "3.0.0",
  "x-stoplight": {
    "id": "dt2qrg4ymqiwk"
  },
  "info": {
    "title": "CTPP",
    "version": "0.1.0",
    "description": "CTPP",
    "contact": {
      "email": "support@macrosysrt.com",
      "name": "Support",
      "url": "https://ctpp.macrosysrt.com"
    },
    "license": {
      "url": "https://ctpp.macrosysrt.com",
      "name": "Private"
    }
  },
  "servers": [
    {
      "url": "https://ctpp.macrosysrt.com/api",
      "description": "Production"
    }
  ],
  "tags": [
    {
      "name": "datasets",
      "description": "There is one dataset for each available year."
    },
    {
      "name": "groups",
      "description": "Groups"
    },
    {
      "name": "data",
      "description": "Groups"
    }
  ],
  "paths": {
    "/datasets": {
      "get": {
        "summary": "List datasets",
        "operationId": "list-datasets",
        "tags": ["datasets"],
        "parameters": [
          {
            "$ref": "#/components/parameters/size"
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "responses": {
          "200": {
            "description": "A paged array of datasets",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-examples": {
                    "Example 1": {
                      "size": 3,
                      "page": 2,
                      "total": 4,
                      "data": [
                        {
                          "year": 2000,
                          "title": "2000 Data",
                          "description": "2000 dataset"
                        }
                      ]
                    }
                  },
                  "properties": {
                    "size": {
                      "type": "integer"
                    },
                    "page": {
                      "type": "integer"
                    },
                    "total": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Dataset"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "size": 2,
                      "page": 1,
                      "total": 4,
                      "data": [
                        {
                          "year": 2016,
                          "title": "2012-2016 (5-year)",
                          "description": "2016 dataset"
                        },
                        {
                          "year": 2013,
                          "title": "2009-2013 County to County Flows",
                          "description": "2013 dataset"
                        }
                      ]
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "description": "Get the metadata of datasets."
      }
    },
    "/datasets/{year}": {
      "get": {
        "summary": "Get a dataset",
        "operationId": "get-dataset-by-id",
        "tags": ["datasets"],
        "parameters": [
          {
            "name": "year",
            "in": "path",
            "description": "Year of the dataset",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "responses": {
          "200": {
            "description": "A object of dataset metadata",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Dataset"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "year": 2016,
                      "title": "2012-2016 (5-year)",
                      "description": "2016 dataset"
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "description": "Get a dataset"
      }
    },
    "/datasets/{year}/groups": {
      "get": {
        "summary": "List groups in a dataset",
        "operationId": "list-groups-of-a-dataset",
        "tags": ["datasets"],
        "parameters": [
          {
            "name": "year",
            "in": "path",
            "required": true,
            "description": "Year of the dataset of the groups to retrieve",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "keyword",
            "in": "query",
            "description": "Filter the groups based on the provided keyword",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "$ref": "#/components/parameters/size"
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "responses": {
          "200": {
            "description": "A paged array of groups",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-examples": {
                    "Example 1": {
                      "size": 2,
                      "page": 1,
                      "total": 195,
                      "data": [
                        {
                          "name": "A101100 ",
                          "description": "Total Population (1)",
                          "universe": "Total Population"
                        },
                        {
                          "name": "A101101",
                          "description": "Age (11)",
                          "universe": "Total Population"
                        }
                      ]
                    }
                  },
                  "properties": {
                    "size": {
                      "type": "integer"
                    },
                    "page": {
                      "type": "integer"
                    },
                    "total": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Group"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "size": 2,
                      "page": 1,
                      "total": 195,
                      "data": [
                        {
                          "name": "A101100 ",
                          "description": "Total Population (1)",
                          "universe": "Total Population"
                        },
                        {
                          "name": "A101101",
                          "description": "Age (11)",
                          "universe": "Total Population"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "description": "Get the groups in a dataset"
      }
    },
    "/datasets/{year}/groups/{id}": {
      "get": {
        "summary": "Get metadata of group",
        "operationId": "find-group-metadata",
        "tags": ["datasets"],
        "parameters": [
          {
            "name": "year",
            "in": "path",
            "description": "The year of dataset of the groups to return",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "id",
            "in": "path",
            "description": "The ID of group returned",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "responses": {
          "200": {
            "description": "A paged array of groups",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Group"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "name": "A101104",
                      "description": "Length of US Residence (6)",
                      "universe": "Total Population"
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "description": "Get the metadata of a group based on group id and dataset year"
      },
      "parameters": []
    },
    "/groups": {
      "get": {
        "summary": "List groups in a dataset",
        "operationId": "list-groups",
        "tags": ["groups"],
        "parameters": [
          {
            "name": "year",
            "in": "query",
            "description": "The year of dataset of the groups to return",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "$ref": "#/components/parameters/size"
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "name": "keyword",
            "in": "query",
            "description": "The keyword required to be in the description of the records",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "responses": {
          "200": {
            "description": "A paged array of groups",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-examples": {
                    "Example 1": {
                      "size": 2,
                      "page": 1,
                      "total": 195,
                      "data": [
                        {
                          "name": "A101100 ",
                          "description": "Total Population (1)",
                          "universe": "Total Population"
                        },
                        {
                          "name": "A101101",
                          "description": "Age (11)",
                          "universe": "Total Population"
                        }
                      ]
                    }
                  },
                  "properties": {
                    "size": {
                      "type": "integer"
                    },
                    "page": {
                      "type": "integer"
                    },
                    "total": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Group"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "size": 2,
                      "page": 1,
                      "total": 195,
                      "data": [
                        {
                          "name": "A101100 ",
                          "description": "Total Population (1)",
                          "universe": "Total Population"
                        },
                        {
                          "name": "A101101",
                          "description": "Age (11)",
                          "universe": "Total Population"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "description": "Get the metadata of the groups of a year"
      }
    },
    "/groups/{id}": {
      "get": {
        "summary": "Get metadata of group",
        "operationId": "find-group-by-id",
        "tags": ["groups"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of group returned",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "year",
            "in": "query",
            "description": "The year of dataset of the groups to return",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "responses": {
          "200": {
            "description": "A group with provided ID",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Group"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "name": "A101101",
                      "description": "Age (11)",
                      "universe": "Total Population"
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "description": "Get the metadata of a group with provided ID of a selected year."
      }
    },
    "/groups/{id}/variables": {
      "get": {
        "summary": "List variables of a group",
        "operationId": "variablesOfGroup",
        "tags": ["groups"],
        "parameters": [
          {
            "name": "year",
            "in": "query",
            "description": "The year of dataset of the groups to return",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "id",
            "in": "path",
            "description": "The ID of selected group",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "$ref": "#/components/parameters/size"
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "responses": {
          "200": {
            "description": "A paged array of variables",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-examples": {
                    "Example 1": {
                      "size": 2,
                      "page": 1,
                      "total": 126,
                      "data": [
                        {
                          "name": "A101110_e1",
                          "label": "Total",
                          "group": "A101110"
                        },
                        {
                          "name": "A101110_m1",
                          "label": "Total",
                          "group": "A101110"
                        }
                      ]
                    }
                  },
                  "properties": {
                    "size": {
                      "type": "integer"
                    },
                    "page": {
                      "type": "integer"
                    },
                    "total": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Variable"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "size": 2,
                      "page": 1,
                      "total": 126,
                      "data": [
                        {
                          "name": "A101110_e1",
                          "label": "Total",
                          "group": "A101110"
                        },
                        {
                          "name": "A101110_m1",
                          "label": "Total",
                          "group": "A101110"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "description": "Get the variables of a group selected by group ID."
      }
    },
    "/groups/{id}/geographies": {
      "get": {
        "summary": "List summary levels of a group",
        "operationId": "list-summary-levels",
        "tags": ["groups"],
        "parameters": [
          {
            "name": "year",
            "in": "query",
            "description": "The year of dataset",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "id",
            "in": "path",
            "description": "The ID of selected group",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "$ref": "#/components/parameters/size"
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "responses": {
          "200": {
            "description": "A paged array of summary levels",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-examples": {
                    "Example 1": {
                      "size": 2,
                      "page": 1,
                      "total": 11,
                      "data": [
                        {
                          "level": "C01",
                          "name": "Nation (US Total)",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C02",
                          "name": "State",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C03",
                          "name": "State-County",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C04",
                          "name": "State-County-MCD (for 12 strong MCD states)",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C05",
                          "name": "State-Place",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C09",
                          "name": "State-PUMA5",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C07",
                          "name": "Metropolitan Statistical Area ",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C08",
                          "name": "Metropolitan Statistical Area \ufffd EACH Principal City",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C11",
                          "name": "State-County-Tract",
                          "category": "RES",
                          "geoType": "SmallGeo"
                        },
                        {
                          "level": "C12",
                          "name": "TAD",
                          "category": "RES",
                          "geoType": "SmallGeo"
                        },
                        {
                          "level": "C13",
                          "name": "TAZ",
                          "category": "RES",
                          "geoType": "SmallGeo"
                        }
                      ]
                    }
                  },
                  "properties": {
                    "size": {
                      "type": "integer"
                    },
                    "page": {
                      "type": "integer"
                    },
                    "total": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/GeographyLevel"
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "size": 2,
                      "page": 1,
                      "total": 11,
                      "data": [
                        {
                          "level": "C01",
                          "name": "Nation (US Total)",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C02",
                          "name": "State",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C03",
                          "name": "State-County",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C04",
                          "name": "State-County-MCD (for 12 strong MCD states)",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C05",
                          "name": "State-Place",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C09",
                          "name": "State-PUMA5",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C07",
                          "name": "Metropolitan Statistical Area ",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C08",
                          "name": "Metropolitan Statistical Area \ufffd EACH Principal City",
                          "category": "RES",
                          "geoType": "LargeGeo"
                        },
                        {
                          "level": "C11",
                          "name": "State-County-Tract",
                          "category": "RES",
                          "geoType": "SmallGeo"
                        },
                        {
                          "level": "C12",
                          "name": "TAD",
                          "category": "RES",
                          "geoType": "SmallGeo"
                        },
                        {
                          "level": "C13",
                          "name": "TAZ",
                          "category": "RES",
                          "geoType": "SmallGeo"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "description": "Get summary levels supported in a group"
      }
    },
    "/data/{year}": {
      "get": {
        "summary": "Get data by table name with summary level",
        "operationId": "getData",
        "tags": ["data"],
        "parameters": [
          {
            "name": "get",
            "in": "query",
            "description": "The data elements to return.  \n  Syntax:  \n-Select two columns from table a101101. Their names are a101101_e1 and a101101_e2.  \n get=[TableColumnsName],[TableColumnsName]  \n-Select all columns from table a101101  \nget=group([TableName])",
            "required": true,
            "schema": {
              "type": "string"
            },
            "examples": {
              "ex1": {
                "value": "a101101_e1,a101101_e2"
              },
              "ex2": {
                "value": "group(a101101)"
              }
            }
          },
          {
            "name": "for",
            "in": "query",
            "description": "Summary levels.  \n\n Syntax: for=[SummaryLevel]:[GeoFilter]",
            "required": true,
            "schema": {
              "type": "string"
            },
            "examples": {
              "ex1": {
                "value": "state:*"
              },
              "ex2": {
                "value": "state:06"
              }
            }
          },
          {
            "name": "in",
            "in": "query",
            "description": "Help select summary levels.  \n \n Syntax: in=[SummaryLevel]:[GeoFilter]",
            "required": false,
            "schema": {
              "type": "string"
            },
            "examples": {
              "ex1": {
                "value": "state:*"
              },
              "ex2": {
                "value": "state:01"
              }
            }
          },
          {
            "name": "bbox",
            "in": "query",
            "description": "The latitude and longitude value of Bounding Box. Bounding box can be used to filter geographies in the query. Bounding box is defined by two sets of coordinates. They are the longitude and latitude of the lower left corner and upper right corner of the box.  \n \nSyntax: bbox=minLon,minLat,maxLon,maxLat",
            "required": false,
            "schema": {
              "type": "string"
            },
            "examples": {
              "ex1": {
                "value": "-75.657349,40.279526,-80.897827,36.650793"
              }
            }
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "format",
            "description": "The response format. Available format options are: array, list and geojson. List is the default option when format is not present in the request.",
            "examples": {
              "ex1": {
                "value": "array"
              }
            }
          },
          {
            "$ref": "#/components/parameters/size"
          },
          {
            "$ref": "#/components/parameters/page"
          },
          {
            "$ref": "#/components/parameters/Accept"
          }
        ],
        "responses": {
          "200": {
            "description": "A paged array of data defined in get parameter",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DataQueryResult"
                },
                "examples": {
                  "Get specific columns data at state level": {
                    "value": {
                      "size": 10,
                      "page": 1,
                      "total": 600,
                      "data": [
                        {
                          "geoid": "C0200US01",
                          "name": "Alabama",
                          "a101101_e1": "4,841,165",
                          "a101101_e2": "976,860"
                        },
                        {
                          "geoid": "C0200US02",
                          "name": "Alaska",
                          "a101101_e1": "736,855",
                          "a101101_e2": "168,125"
                        },
                        {
                          "geoid": "C0200US04",
                          "name": "Arizona",
                          "a101101_e1": "6,728,575",
                          "a101101_e2": "1,437,740"
                        },
                        {
                          "geoid": "C0200US05",
                          "name": "Arkansas",
                          "a101101_e1": "2,968,470",
                          "a101101_e2": "629,165"
                        },
                        {
                          "geoid": "C0200US06",
                          "name": "California",
                          "a101101_e1": "38,654,205",
                          "a101101_e2": "8,088,460"
                        },
                        {
                          "geoid": "C0200US08",
                          "name": "Colorado",
                          "a101101_e1": "5,359,295",
                          "a101101_e2": "1,113,735"
                        },
                        {
                          "geoid": "C0200US09",
                          "name": "Connecticut",
                          "a101101_e1": "3,588,570",
                          "a101101_e2": "676,645"
                        },
                        {
                          "geoid": "C0200US10",
                          "name": "Delaware",
                          "a101101_e1": "934,695",
                          "a101101_e2": "181,655"
                        },
                        {
                          "geoid": "C0200US11",
                          "name": "District of Columbia",
                          "a101101_e1": "659,010",
                          "a101101_e2": "104,230"
                        },
                        {
                          "geoid": "C0200US12",
                          "name": "Florida",
                          "a101101_e1": "19,934,450",
                          "a101101_e2": "3,595,150"
                        }
                      ]
                    }
                  },
                  "Get all columns at State-County level": {
                    "value": {
                      "size": 5,
                      "page": 1,
                      "total": 58,
                      "data": [
                        {
                          "geoid": "C0300US06001",
                          "name": "Alameda County, California",
                          "A101101_e5": "88,145",
                          "A101101_e6": "256,825",
                          "A101101_e7": "237,845",
                          "A101101_e8": "329,950",
                          "A101101_e9": "88,960",
                          "A101101_m5": "+/-966",
                          "A101101_m6": "*****",
                          "A101101_m7": "*****",
                          "A101101_m8": "+/-1,427",
                          "A101101_e1": "1,605,215",
                          "A101101_m9": "+/-1,427",
                          "A101101_e2": "306,970",
                          "A101101_e11": "84,340",
                          "A101101_e3": "37,240",
                          "A101101_e10": "115,360",
                          "A101101_e4": "59,580",
                          "A101101_m1": "*****",
                          "A101101_m2": "+/-677",
                          "A101101_m3": "+/-678",
                          "A101101_m11": "*****",
                          "A101101_m4": "+/-966",
                          "A101101_m10": "*****"
                        },
                        {
                          "geoid": "C0300US06003",
                          "name": "Alpine County, California",
                          "A101101_e5": "45",
                          "A101101_e6": "105",
                          "A101101_e7": "130",
                          "A101101_e8": "225",
                          "A101101_e9": "80",
                          "A101101_m5": "+/-25",
                          "A101101_m6": "+/-50",
                          "A101101_m7": "+/-50",
                          "A101101_m8": "+/-75",
                          "A101101_e1": "1,185",
                          "A101101_m9": "+/-29",
                          "A101101_e2": "215",
                          "A101101_e11": "95",
                          "A101101_e3": "55",
                          "A101101_e10": "150",
                          "A101101_e4": "75",
                          "A101101_m1": "+/-191",
                          "A101101_m2": "+/-61",
                          "A101101_m3": "+/-24",
                          "A101101_m11": "+/-51",
                          "A101101_m4": "+/-49",
                          "A101101_m10": "+/-54"
                        },
                        {
                          "geoid": "C0300US06005",
                          "name": "Amador County, California",
                          "A101101_e5": "1,300",
                          "A101101_e6": "3,475",
                          "A101101_e7": "3,990",
                          "A101101_e8": "8,655",
                          "A101101_e9": "3,480",
                          "A101101_m5": "+/-130",
                          "A101101_m6": "+/-166",
                          "A101101_m7": "+/-159",
                          "A101101_m8": "+/-346",
                          "A101101_e1": "36,965",
                          "A101101_m9": "+/-286",
                          "A101101_e2": "5,080",
                          "A101101_e11": "3,515",
                          "A101101_e3": "665",
                          "A101101_e10": "5,625",
                          "A101101_e4": "1,170",
                          "A101101_m1": "*****",
                          "A101101_m2": "+/-105",
                          "A101101_m3": "+/-99",
                          "A101101_m11": "+/-65",
                          "A101101_m4": "+/-161",
                          "A101101_m10": "+/-87"
                        },
                        {
                          "geoid": "C0300US06007",
                          "name": "Butte County, California",
                          "A101101_e5": "20,815",
                          "A101101_e6": "27,380",
                          "A101101_e7": "23,190",
                          "A101101_e8": "41,250",
                          "A101101_e9": "14,430",
                          "A101101_m5": "+/-667",
                          "A101101_m6": "+/-164",
                          "A101101_m7": "+/-201",
                          "A101101_m8": "+/-597",
                          "A101101_e1": "223,875",
                          "A101101_m9": "+/-575",
                          "A101101_e2": "39,945",
                          "A101101_e11": "16,930",
                          "A101101_e3": "5,525",
                          "A101101_e10": "21,215",
                          "A101101_e4": "13,195",
                          "A101101_m1": "*****",
                          "A101101_m2": "+/-257",
                          "A101101_m3": "+/-268",
                          "A101101_m11": "+/-82",
                          "A101101_m4": "+/-680",
                          "A101101_m10": "+/-100"
                        },
                        {
                          "geoid": "C0300US06009",
                          "name": "Calaveras County, California",
                          "A101101_e5": "1,580",
                          "A101101_e6": "3,780",
                          "A101101_e7": "4,045",
                          "A101101_e8": "10,620",
                          "A101101_e9": "4,165",
                          "A101101_m5": "+/-171",
                          "A101101_m6": "+/-196",
                          "A101101_m7": "+/-210",
                          "A101101_m8": "+/-542",
                          "A101101_e1": "44,785",
                          "A101101_m9": "+/-468",
                          "A101101_e2": "6,945",
                          "A101101_e11": "4,180",
                          "A101101_e3": "1,095",
                          "A101101_e10": "7,065",
                          "A101101_e4": "1,310",
                          "A101101_m1": "*****",
                          "A101101_m2": "+/-168",
                          "A101101_m3": "+/-138",
                          "A101101_m11": "+/-120",
                          "A101101_m4": "+/-164",
                          "A101101_m10": "+/-204"
                        }
                      ]
                    }
                  },
                  "Select specific columns at State-Place level": {
                    "value": {
                      "size": 5,
                      "page": 1,
                      "total": 29574,
                      "data": [
                        {
                          "geoid": "C0500US0100100",
                          "name": "Abanda CDP, Alabama",
                          "a101101_e1": "150",
                          "a101101_e2": "35"
                        },
                        {
                          "geoid": "C0500US0100124",
                          "name": "Abbeville city, Alabama",
                          "a101101_e1": "2,625",
                          "a101101_e2": "455"
                        },
                        {
                          "geoid": "C0500US0100460",
                          "name": "Adamsville city, Alabama",
                          "a101101_e1": "4,420",
                          "a101101_e2": "770"
                        },
                        {
                          "geoid": "C0500US0100484",
                          "name": "Addison town, Alabama",
                          "a101101_e1": "755",
                          "a101101_e2": "100"
                        },
                        {
                          "geoid": "C0500US0100676",
                          "name": "Akron town, Alabama",
                          "a101101_e1": "250",
                          "a101101_e2": "30"
                        }
                      ]
                    }
                  },
                  "Filter to get spatial data with bounding box": {
                    "value": {
                      "size": 5,
                      "page": 1,
                      "total": 3,
                      "data": [
                        {
                          "geoid": "C0300US42067",
                          "name": "Juniata County, Pennsylvania",
                          "A101110_e1": "24,810",
                          "INTPTLON": "-077.4004377",
                          "a101110_e1": "24,810"
                        },
                        {
                          "geoid": "C0300US51790",
                          "name": "Staunton city, Virginia",
                          "A101110_e1": "24,235",
                          "INTPTLON": "-079.0615010",
                          "a101110_e1": "24,235"
                        },
                        {
                          "geoid": "C0300US54097",
                          "name": "Upshur County, West Virginia",
                          "A101110_e1": "24,630",
                          "INTPTLON": "-080.2313352",
                          "a101110_e1": "24,630"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Get data by table name of a year at different summary levels.\n\n## Examples:  \n### 1. Get specific columns data at state level:  \n\n<em>/data/2016?get=a101101_e1,a101101_e2&for=state:*&size=10&page=1</em>  \nThe <b>state</b> parameter is to select the states.  \nSpecify <b>state</b> parameter with two digits number: *<b>state:06,07</b>*\n\n\n\n### 2. Get all columns at State-County level:  \n\n\n<em>/data/2016?get=group(a101101)&for=county:*&in=state:06&size=5&page=1</em>  \nThe <b>county</b> parameter is to select the counties in selected state.  \nSpecify <b>county</b> parameter with three digits number: <em><b>county:005,006</b></em>\n\n### 3. Select specific columns at State-Place level:  \n\n<em>/data/2016?get=a101101_e1,a101101_e2&for=place:*&in=state:*&size=5&page=1</em>  \nThe <b>place</b> parameter is to select the places in selected state.  \nSpecify <b>place</b> parameter with five digits number: <em><b>county:00100,00124</b></em>\n\n### 4. Filter to get spatial data with bounding box: \n\n<em>/data/2016?format=array&for=county:*&get=A101110_e1,INTPTLON&A101110_e1=24015:25000  \n&bbox=-75.657349,40.279526,-80.897827,36.650793&size=5&page=1</em>  \nThe <b>bbox</b> parameter is to specify the value of the Bounding Box.  \nSpecify <b>bbox</b> parameter with Longitude and Latitude values: <em><b>bbox=-75.657349,40.279526,-80.897827,36.650793</b></em>"
      },
      "parameters": [
        {
          "schema": {
            "type": "string",
            "example": "2016"
          },
          "name": "year",
          "in": "path",
          "required": true,
          "description": "Specify a year to get the data of  that year."
        }
      ]
    }
  },
  "components": {
    "schemas": {
      "Variable": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "group": {
            "type": "string"
          }
        }
      },
      "GeographyLevel": {
        "type": "object",
        "properties": {
          "level": {
            "type": "string"
          },
          "hierarchy": {
            "type": "string"
          },
          "limit": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "Dataset": {
        "type": "object",
        "properties": {
          "year": {
            "type": "integer",
            "format": "int32"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "title": "Dataset",
        "description": "Metadata of dataset",
        "x-examples": {
          "example-1": {
            "year": 2016,
            "title": "2012-2016 (5-year)",
            "description": "2016 dataset"
          }
        }
      },
      "Group": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "universe": {
            "type": "string"
          }
        },
        "title": "Group",
        "description": "Metadata of a group",
        "x-examples": {
          "example-1": {
            "name": "A101102",
            "description": "Urban/Rural residence (3)",
            "universe": "Total Population"
          }
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "string"
          },
          "status": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "path": {
            "type": "string"
          }
        }
      },
      "DataQueryResult": {
        "title": "DataQueryResult",
        "x-stoplight": {
          "id": "xzr0w5iors9i2"
        },
        "type": "object",
        "properties": {
          "size": {
            "type": "integer"
          },
          "page": {
            "type": "integer"
          },
          "total": {
            "type": "integer"
          },
          "data": {
            "type": "array",
            "items": {}
          }
        }
      }
    },
    "securitySchemes": {
      "API-Key-1": {
        "name": "x-api-key",
        "type": "apiKey",
        "in": "header"
      }
    },
    "parameters": {
      "page": {
        "name": "page",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer"
        },
        "description": "Page number of the results to fetch."
      },
      "size": {
        "name": "size",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string"
        },
        "description": "The number of results per page. "
      },
      "Accept": {
        "name": "Accept",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "application/json",
          "enum": ["application/json", "application/xml"],
          "default": "application/json"
        },
        "description": "Setting to application/json is recommended."
      }
    }
  },
  "security": [
    {
      "API-Key-1": []
    }
  ]
}
